### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ShalokShalom**
Add info about abandonment and new alternative, now default in KWin.

### CODE REVIEW

**Comment by appetrosyan** [comment]
I'm quite sure that the KDE tiling implementation is nothing like Krohnkite, and this notice of abandonment was premature. I think it's a good idea to close it for now.

**Comment by ShalokShalom** [comment]
This project is dead

**Comment by appetrosyan** [comment]
> This project is dead

This project, 
1) Runs on the latest version of Plasma. 
2) Runs reliably, which cannot be said of either bismuth or Polonium. 
3) The "correction" that you introduce is misleading: the tiling facilities in KWin are nothing compared to the automatic tiling that krohnkite offers. The development of krohnkite may have entered a passive phase, and it is preferable to get this sort of functionality as a baseline inside of KWin. **However** the current state of affairs, is that KWin's implementation is undercooked, and Krohnkite works well.

**Comment by appetrosyan** [comment]
Thank you :)

**Pull request closed without merging**
